name: ptv3
in_channels: 4
intensity_channel: false
enc_channels: [32, 64, 128, 256, 512]
enc_depths: [2, 2, 2, 6, 2]
dec_channels: [64, 64, 128, 256]
dec_depths: [2, 2, 2, 2]
patch_size: 1024
enable_flash: true
grid_size: 0.02
latent_dim: 512

color_head:
  enabled: false
  rgb_channels: 3
